- name: Klasorleri Listele (Hata Ayiklama)
        run: ls -R # Bu komut GitHub'ın hangi dosyaları gördüğünü bize siyah ekranda yazdıracak

      - name: Java Derle
        run: |
          find . -name "MerhabaDevops.java" # Dosyayı otomatik bulsun
          javac $(find . -name "MerhabaDevops.java")
          java -cp app MerhabaDevops