name: DevOps-Projesi

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari indir
        uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dosyalari Listele
        run: ls -R

      - name: Java Derle ve Calistir
        run: |
          javac app/MerhabaDevops.java
          java -cp app MerhabaDevops
          
          - name: Kod Kalite Kontrol (Test)
        run: |
          if grep -q "DevOps" app/MerhabaDevops.java; then
            echo "✅ Test Basarili: Kod icinde DevOps anahtar kelimesi bulundu."
          else
            echo "❌ Test Basarisiz: Kod icinde 'DevOps' kelimesi eksik!"
            exit 1
          fi

      - name: Docker Hub'a Login Ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Imajini Hazirla ve Firlat
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest