name: DevOps-Projesi

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari indir
        uses: actions/checkout@v3

      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dosyalari Listele
        run: ls -R

      - name: Java Derle
        run: |
          javac app/MerhabaDevops.java
          java -cp app MerhabaDevops